### ISSUE TITLE
nmf error

### ISSUE THREAD

**Issue by voluptatis** [carmonalab/GeneNMF#1]
Expecting a single value: [extent=0].

**Comment by mass-a** [comment]
Hello, can you give more context? what function returns this warning/error? a reproducible example would be useful.

**Comment by mianaz** [comment]
I encountered the same problem. The error is reproducible with the sample data: data(sampleObj) sampleObj <- runNMF(sampleObj)
Error: Expecting a single value: [extent=0].

**Comment by whitneyt1** [comment]
I had the same issue when running
```
 geneNMF.programs <- multiNMF(sampleObj.list, k=4:12, assay='RNA', slot='data',
                             hvg.blocklist= exclude_genes)
```
`library(RcppML)` fixed this issue.
