### ISSUE TITLE
Error in `$<-`(`*tmp*`, h, value = `*vtmp*`)

### ISSUE THREAD

**Issue by cjhong** [carmonalab/GeneNMF#13]
First of all, thank you for the great NMF development for a single-cell analysis

I installed GeneNMF and RcppML from github via dev/remotes.
I got the following error message and I guess something related w/ the other package or dependency issue.

# ------
library(GeneNMF)
library(RcppML)
library(Seurat)
library(ggplot2)
library(UCell)
library(patchwork)
library(Matrix)
library(viridis)

options(timeout=1000)

ddir <- "input"
data.path <- sprintf("%s/pbmc_multimodal.downsampled20k.seurat.rds", ddir)

if (!file.exists(data.path)) {
  dir.create(ddir)
  dataUrl <- "https://www.dropbox.com/s/akzu3hp4uz2mpkv/pbmc_multimodal.downsampled20k.seurat.rds?dl=1"
  download.file(dataUrl, data.path)
}

seu <- readRDS(data.path)
seu.list <- SplitObject(seu, split.by = "donor")

geneNMF.programs <- multiNMF(seu.list, assay="SCT", slot="data", k=4:9, nfeatures = 1000)

Error in `$<-`(`*tmp*`, h, value = `*vtmp*`) : 
  no method for assigning subsets of this S4 class

**Comment by mass-a** [comment]
Rereading more carefully your message, I see that you are installing RcppML from GitHub.
Please use instead the release version of RcppML from CRAN: `install.packages("RcppML")`

**Comment by cjhong** [comment]
I reinstalled the RcppML from CRAN. It works now! Thank you
