### ISSUE TITLE
How to determine number of MP?

### ISSUE THREAD

**Issue by vincentguo0418** [carmonalab/GeneNMF#2]
Hi,

I have two questions:
1. How to determine a reasonable number of MetaProgram (i.e., nprograms in function getMetaPrograms)?
2. How to cite your work?

Thanks

**Comment by mass-a** [comment]
Hello,
thanks for your interest in our tool. 
To get an idea on the number of MPs, it's useful to inspect the similarity between individual NMF programs, for example as shown in the heatmap from [this demo](https://carmonalab.github.io/GeneNMF.demo/NMF_demo_PBMC.html#consistent-nmf-meta-programs-across-multiple-samples). Here you see 8 to 12 "blocks" of programs, which indicates that a reasonable number of MPs should be in this ballpark. Depending on the desired level of resolution (i.e. few broad MPs, or more specific ones), you can then decide where to cut the hierarchical tree of programs into consensus MPs. After running GeneNMF, you can also look at the MP metrics (stored in `geneNMF.metaprograms$metaprograms.metrics`), to see if the MPs are too broad, or redundant, and possibly iterate the analysis with a different target number of MPs.

As for citing GeneNMF in your work, we are currently working on a publication describing the method. In the meantime, you can use the information returned by: `citation("GeneNMF")`

Best
-m

**Comment by mass-a** [comment]
To follow up on your second question, there is now a preprint describing GeneNMF and its application to discover gene programs in BCC:

**Wounding triggers invasive progression in human basal cell carcinoma**. Laura Yerly, Massimo Andreatta, Josep Garnica, Jeremy Di Domizio, Michel Gilliet, Santiago J Carmona, Francois Kuonen. **bioRxiv (2024)**: [10.1101/2024.05.31.596823](https://doi.org/10.1101/2024.05.31.596823)
