### ISSUE TITLE
GeneNMF requires R 4.3 or higher

### ISSUE THREAD

**Issue by metaspine** [carmonalab/GeneNMF#3]
Dear author
   This is a great toolkit! However, when I library it in R, error occur.
   The code is [
         library(GeneNMF,lib.loc = "/share/home/User/miniconda3/envs/R4.3/lib/R/library")
         Error: This is R 4.2.2, package ‘GeneNMF’ needs >= 4.3.0]
   Is there a test of R version in your package (i gusses?), which make me can not library it

**Comment by mass-a** [comment]
Hello,
yes the package requires R 4.3 or higher.
Do you have a way of updating your R version? Note that you can also have multiple R versions installed at the same time (e.g. on [Linux](https://support.posit.co/hc/en-us/articles/215488098-Installing-multiple-versions-of-R-on-Linux) or [Mac](https://rud.is/rswitch/)).

**Comment by metaspine** [comment]
Sorry, i tried it before. But i do not have enough access to update R. I have to use conda environment and library GeneNMF by command line, which is not convenient...
