### ISSUE TITLE
normalisation method query

### ISSUE THREAD

**Issue by Shubhra1994** [carmonalab/GeneNMF#6]
Hello,
In the html tutorial [here](https://carmonalab.github.io/GeneNMF.demo/NMF_demo_PBMC.html#consistent-nmf-meta-programs-across-multiple-samples) the assay used is sct which is sc transformed data.

Is it necessary to use SCT or the lognormalisation pipeline of seurat works well too?

What do you suggest to use?

**Comment by mass-a** [comment]
Hello!
we don't have a strong preference/recommendation for the normalization method to apply prior to GeneNMF. The default is "RNA" (standard log-normalization) but also SCT as in the tutorial should work fine.
There are several studies comparing normalization methods for scRNA-seq (e.g. https://www.nature.com/articles/s41592-023-01814-1), but I am not aware of any that looks specifically at normalization in the context of NMF. When in doubt, I would go for a simple log-normalization.
